### ISSUE TITLE
Timeout error to show a sharepoint page

### ISSUE THREAD

**Issue by MyKeySoftMK** [estruyf/testing-microsoft365-playwright-template#1]
Thanks for your work here. I try to adapted to my enviroment.

It works fine - my company sharepoint page will open (i see it in palywright ui) - but the `await page.waitForURL(process.env.M365_PAGE_URL || "");` in the `login.setup.ts` will not finished and go to the next step.

I try to increase the timeout - but not success

Did MS make some changes for that?

**Comment by estruyf** [comment]
@MyKeySoftMK No, this should still work fine. I've got multiple tests on various tenants running like this.

What might happen is that MS redirects you to a page where your URL is different from an exact match. You can always verify this if you run in non-headless mode locally, or you could verify on the URL as follows: `await page.waitForURL(url => url.href.toLowerCase().includes((process.env.M365_PAGE_URL || "").toLowerCase())`

**Comment by MyKeySoftMK** [comment]
Yes - that was the problem - the redirect was the reason.

Thanks for the fast reply :-)
