### ISSUE TITLE
Test chain is not visible/running

### ISSUE THREAD

**Issue by MyKeySoftMK** [estruyf/testing-microsoft365-playwright-template#2]
My Config is
```
projects: [
    {
      name: "setup",
      testMatch: /login\.setup.ts/,
    },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'],
	  storageState: AuthFile,
	  },
	  dependencies: ["setup"],
    },
```

When I start playwright in ui mode, then i only see the `authenticate` (that now works fine). But all my other tests not seen.

When I remove the `testMatch: /login\.setup.ts/,` I see all my tests (not the login.setup.ts) - but when I run my test (page-load.spec.ts) then the Login is not execute.

What I have do wrong or forget?

**Comment by estruyf** [comment]
It might be something in the UI. On the UI, you will see `projects` and if you click on it, you can select all the projects you want to view.

![image](https://github.com/user-attachments/assets/1c9f771b-bfef-4689-9a6b-dc3e66f72f3d)

**Comment by MyKeySoftMK** [comment]
Oh sorry - that I dont see 

Thanks
